/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Browser`; params?: Router.UnknownInputParams; } | { pathname: `/components/KeyProvider`; params?: Router.UnknownInputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/WalletContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/config`; params?: Router.UnknownInputParams; } | { pathname: `/utils/arraysOfObjectsAreEqual`; params?: Router.UnknownInputParams; } | { pathname: `/utils/deterministicColor`; params?: Router.UnknownInputParams; } | { pathname: `/utils/deterministicImage`; params?: Router.UnknownInputParams; } | { pathname: `/utils/exportDataToFile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/fetchAndCacheAppData`; params?: Router.UnknownInputParams; } | { pathname: `/utils/getApps`; params?: Router.UnknownInputParams; } | { pathname: `/utils/isImageUrl`; params?: Router.UnknownInputParams; } | { pathname: `/utils/parseAppManifest`; params?: Router.UnknownInputParams; } | { pathname: `/utils/useBreakpoints`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validateTrust`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Browser`; params?: Router.UnknownOutputParams; } | { pathname: `/components/KeyProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/WalletContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/config`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/arraysOfObjectsAreEqual`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/deterministicColor`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/deterministicImage`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/exportDataToFile`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/fetchAndCacheAppData`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/getApps`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/isImageUrl`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/parseAppManifest`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/useBreakpoints`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/validateTrust`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Browser${`?${string}` | `#${string}` | ''}` | `/components/KeyProvider${`?${string}` | `#${string}` | ''}` | `/components/Scanner${`?${string}` | `#${string}` | ''}` | `/context/UserContext${`?${string}` | `#${string}` | ''}` | `/context/WalletContext${`?${string}` | `#${string}` | ''}` | `/context/config${`?${string}` | `#${string}` | ''}` | `/utils/arraysOfObjectsAreEqual${`?${string}` | `#${string}` | ''}` | `/utils/deterministicColor${`?${string}` | `#${string}` | ''}` | `/utils/deterministicImage${`?${string}` | `#${string}` | ''}` | `/utils/exportDataToFile${`?${string}` | `#${string}` | ''}` | `/utils/fetchAndCacheAppData${`?${string}` | `#${string}` | ''}` | `/utils/getApps${`?${string}` | `#${string}` | ''}` | `/utils/isImageUrl${`?${string}` | `#${string}` | ''}` | `/utils/parseAppManifest${`?${string}` | `#${string}` | ''}` | `/utils/useBreakpoints${`?${string}` | `#${string}` | ''}` | `/utils/validateTrust${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Browser`; params?: Router.UnknownInputParams; } | { pathname: `/components/KeyProvider`; params?: Router.UnknownInputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/WalletContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/config`; params?: Router.UnknownInputParams; } | { pathname: `/utils/arraysOfObjectsAreEqual`; params?: Router.UnknownInputParams; } | { pathname: `/utils/deterministicColor`; params?: Router.UnknownInputParams; } | { pathname: `/utils/deterministicImage`; params?: Router.UnknownInputParams; } | { pathname: `/utils/exportDataToFile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/fetchAndCacheAppData`; params?: Router.UnknownInputParams; } | { pathname: `/utils/getApps`; params?: Router.UnknownInputParams; } | { pathname: `/utils/isImageUrl`; params?: Router.UnknownInputParams; } | { pathname: `/utils/parseAppManifest`; params?: Router.UnknownInputParams; } | { pathname: `/utils/useBreakpoints`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validateTrust`; params?: Router.UnknownInputParams; };
    }
  }
}
