/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/apps`; params?: Router.UnknownInputParams; } | { pathname: `/identity`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/security`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/trust`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/apps` | `/apps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/identity` | `/identity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trust` | `/trust`; params?: Router.UnknownInputParams; } | { pathname: `/auth/phone`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/apps`; params?: Router.UnknownOutputParams; } | { pathname: `/identity`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/security`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/trust`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/apps` | `/apps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/identity` | `/identity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trust` | `/trust`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/phone`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/apps${`?${string}` | `#${string}` | ''}` | `/identity${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/security${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/trust${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/apps${`?${string}` | `#${string}` | ''}` | `/apps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/identity${`?${string}` | `#${string}` | ''}` | `/identity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/security${`?${string}` | `#${string}` | ''}` | `/security${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trust${`?${string}` | `#${string}` | ''}` | `/trust${`?${string}` | `#${string}` | ''}` | `/auth/phone${`?${string}` | `#${string}` | ''}` | `/auth/otp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/apps`; params?: Router.UnknownInputParams; } | { pathname: `/identity`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/security`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/trust`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/apps` | `/apps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/identity` | `/identity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trust` | `/trust`; params?: Router.UnknownInputParams; } | { pathname: `/auth/phone`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; };
    }
  }
}
