name: iOS Deploy

on:
  workflow_dispatch:

jobs:
  build-and-submit-ios:
    runs-on: macos-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
      EXPO_ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
      EXPO_APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      EXPO_APPLE_TEAM_TYPE: ${{ secrets.APPLE_TEAM_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore ASC API key from secret
        shell: bash
        env:
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
        run: |
          set -euo pipefail
          mkdir -p "$RUNNER_TEMP/asc"
          # Write the .p8 to a temp file from base64 secret
          echo "$ASC_KEY_P8_BASE64" | base64 --decode > "$RUNNER_TEMP/asc/AuthKey_${EXPO_ASC_KEY_ID}.p8"
          # Expose path to EAS via env
          echo "EXPO_ASC_API_KEY_PATH=$RUNNER_TEMP/asc/AuthKey_${EXPO_ASC_KEY_ID}.p8" >> "$GITHUB_ENV"

      - name: EAS Build (iOS production)
        run: npx eas build --platform ios --profile production --non-interactive

      - name: EAS Submit (iOS production)
        run: npx eas submit --platform ios --profile production --non-interactive --latest --asc-app-id ${{ secrets.ASC_APP_ID }}